//LOGIN STADOS
export const LOGUEO_DE_USUARIO='LOGUEO_DE_USUARIO';
export const ESTADO_LOGUEO ='ESTADO_LOGUEO';
//INFORMATION
export const PETICION_USUARIOS_LOGINS='PETICION_USUARIOS_LOGINS';
export const PETICION_MATERIAS_DOCENTE='PETICION_MATERIAS_DOCENTE';

export const INSERTAR_MATERIA_OBJETO='INSERTAR_MATERIA_OBJETO';
export const BORRAR_MATERIA_OBJETO='BORRAR_MATERIA_OBJETO';
export const BORRAR_DOCENTE_OBJETO='BORRAR_DOCENTE_OBJETO';

export const RESETEAR_VARIABLES_ESTADO='RESETEAR_VARIABLES_ESTADO';
export const RESETEAR_VARIABLES_ESTADO_DATES='RESETEAR_VARIABLES_ESTADO_DATES'

export const ENLISTAR_PLATAFORMAS='ENLISTAR_PLATAFORMAS';
export const INSERTAR_PLATAFORMAS='INSERTAR_PLATAFORMAS';
export const BORRAR_PLATAFORMAS='BORRAR_PLATAFORMAS';

export const DESCARGAR_LISTA_DOCENTE='DESCARGAR_LISTA_DOCENTE';
export const LISTAR_DATOS_DOCENTE='LISTAR_DATOS_DOCENTE';
export const RESETEAR_DATOS_DOCENTE='RESETEAR_dATOS_DOCENTE'

export const SUBIR_ARCHIVO='SUBIR_ARCHIVO'